#@TYPE: Machine
#@NAME: AESYS Generic x64 board
#@DESCRIPTION: Machine configuration for generic x64 board
#@MAINTAINER: morix.dev <morix.dev@gmail.com>

DEFAULTTUNE ?= "core2-64"
require conf/machine/include/x86/tune-core2.inc
require conf/machine/include/genericx86-common.inc

MACHINEOVERRIDES =. "genericx86-64:"

#For runqemu
QB_SYSTEM_NAME = "qemu-system-x86_64"

# Specifica che il bootloader desiderato è u-boot
EFI_PROVIDER = "u-boot"

# Indica a U-Boot di generare il payload EFI (fondamentale per x86)
UBOOT_ARCH = "x86"
UBOOT_MACHINE = "efi-x86_payload64_defconfig"
UBOOT_MAKE_TARGET = "u-boot-payload.efi"

# Rimuove la compilazione della directory examples
EXTRA_OEMAKE:append:pn-u-boot = " EXAMPLES="
EXTRA_OEMAKE:append:pn-u-boot = " STUB_ARCH=i386"

# Rimuovi l'eredità di grub se presente e assicurati che l'immagine supporti EFI
MACHINE_FEATURES:append = " efi"
IMAGE_BOOT_POLICY = "u-boot"

APPEND:append = " console=tty0 console=ttyS0,115200 "

# Need to remove all extra args from WIC command, otherwise
# base recipes will include the default option for not touching fstab
# which we do not want in this case
WIC_CREATE_EXTRA_ARGS = ""

# Set initial ramdisk image
INITRAMFS_IMAGE = "aesys-initramfs-image"

# Since we want to insert into WIC an artifact (squashfs of the root filesystem)
# built by a task that do_image_wic does not depend on, then we need to
# add an extra dependency
do_image_wic[recrdeptask] += "do_image_squashfs"

# Specify custom disk partitioning
WKS_FILE = "aesys-x64.wks.in"
WKS_FILE_DEPENDS:append = " \
    squashfs-tools-native \
    ${INITRAMFS_IMAGE} \
"

# Include the initial ramdisk image in the boot partition
IMAGE_BOOT_FILES:append = " \
    u-boot-payload.efi;EFI/BOOT/bootx64.efi \
    bzImage;bzImage \
    initramfs.cpio.gz;initram.img \
    ${IMGDEPLOYDIR}/${IMAGE_NAME}.squashfs;rootfs.squashfs \
"


