#!/bin/bash

set -e

case "$2" in
up)
	run-parts -a "$1" -a "$2" /etc/ifplugd/action.d/
	;;
down)
	run-parts --reverse -a "$1" -a "$2" /etc/ifplugd/action.d/
	;;
*)
	echo "ifplugd.action: Incorrect action argument" >&2
	exit 1
	;;
esac