FILESEXTRAPATHS:prepend := "${THISDIR}/files:"

# Disable dhcpcd by default (we do not want dhcpcd to run in manager mode, but only upon specific interface request)
SYSTEMD_AUTO_ENABLE:${PN} = "disable"

RDEPENDS:${PN} += "bash"

SRC_URI += " \
    file://dhcpcd.enter-hook \
    file://dhcpcd.exit-hook \
    file://refresh_dhcpcd_conf.sh \
    file://static_wired0 \
    file://static_wired1 \
    file://static_mlan0 \
    file://mode_wired0 \
    file://mode_wired1 \
    file://mode_mlan0 \
"

FILES:${PN} += " \
    ${sysconfdir}/dhcpcd.enter-hook \
    ${sysconfdir}/dhcpcd.exit-hook \
    ${bindir}/refresh_dhcpcd_conf.sh \
    /data/.sys/dhcpcd/static_wired0 \
    /data/.sys/dhcpcd/static_wired1 \
    /data/.sys/dhcpcd/static_mlan0 \
    /data/.sys/dhcpcd/mode_wired0 \
    /data/.sys/dhcpcd/mode_wired1 \
    /data/.sys/dhcpcd/mode_mlan0 \
"

do_install:append() {

    # Customization
    echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "# AESYS customization" >> ${D}/${sysconfdir}/dhcpcd.conf

    echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "# Toggle following lines for enabling dhcpcd debugging" >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "#debug" >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "#logfile /tmp/dhdpcd.log" >> ${D}/${sysconfdir}/dhcpcd.conf

    echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "hostname" >> echo >> ${D}/${sysconfdir}/dhcpcd.conf

    echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "option ntp_servers" >> echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "option log_servers" >> echo >> ${D}/${sysconfdir}/dhcpcd.conf

    echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "timeout 0" >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "reboot 60" >> ${D}/${sysconfdir}/dhcpcd.conf

    echo >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "# Do not edit this file beyond the following line, since it is being re-generated at runtime" >> ${D}/${sysconfdir}/dhcpcd.conf
    echo "#-----" >> ${D}/${sysconfdir}/dhcpcd.conf
    echo >> ${D}/${sysconfdir}/dhcpcd.conf
}

do_install:append(){

    install -d ${D}${sysconfdir}/
    install -m 0644 ${UNPACKDIR}/dhcpcd.enter-hook ${D}${sysconfdir}
    install -m 0644 ${UNPACKDIR}/dhcpcd.exit-hook ${D}${sysconfdir}

    install -d ${D}${bindir}/
    install -m 0755 ${UNPACKDIR}/refresh_dhcpcd_conf.sh ${D}${bindir}

    install -d ${D}/data/.sys/dhcpcd
    install -m 0644 ${UNPACKDIR}/static_wired0 ${D}/data/.sys/dhcpcd/
    install -m 0644 ${UNPACKDIR}/static_wired1 ${D}/data/.sys/dhcpcd/
    install -m 0644 ${UNPACKDIR}/static_mlan0 ${D}/data/.sys/dhcpcd/
    install -m 0644 ${UNPACKDIR}/mode_wired0 ${D}/data/.sys/dhcpcd/
    install -m 0644 ${UNPACKDIR}/mode_wired1 ${D}/data/.sys/dhcpcd/
    install -m 0644 ${UNPACKDIR}/mode_mlan0 ${D}/data/.sys/dhcpcd/
}