# Aesys DISTRO based on fsl-imx-wayland
include conf/distro/fsl-imx-wayland.conf

DISTRO = "aesys-distro"
DISTRO_NAME = "Aesys Linux"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "aesys-distro"

# Set preferred recipes version for this distro
PREFERRED_VERSION_neatvnc = "0.6.0%"

# Ensure SPDX and CVE-check
INHERIT_DISTRO:append = " create-spdx cve-check "

# Add pulseaudio
DISTRO_FEATURES:append = "dbus pulseaudio"

# Remove nfs from DISTRO_FEATURES (since it implies rpcbind which we could get rid of due to OS harderning)
DISTRO_FEATURES:remove = "nfs"

# Remote ptest from DISTRO_FEATURES (for minimizing the size of produced images)
DISTRO_FEATURES:remove = "ptest"

# Force rsyslog as syslog manager, for OS hardening purposes
# (the default is sysklog but it seems quite an outdated project)
VIRTUAL-RUNTIME_syslog = "rsyslog"