# Aesys DISTRO based on fsl-imx-wayland
include conf/distro/fsl-imx-wayland.conf

DISTRO = "aesys-distro"
DISTRO_NAME = "Aesys Linux"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "aesys-distro"

# Set preferred recipes version for this distro
PREFERRED_VERSION_neatvnc = "0.6.0%"