#!/bin/bash

# Update routers
if [ -f /var/run/gw.$IFACE ]; then
    rm /var/run/gw.$IFACE ;
fi

if [ "$METHOD" == "static" ] && [ ! -z "$IF_GATEWAY" ]; then
    echo $IF_GATEWAY > /var/run/gw.$IFACE
fi

